name: Workflow Generator Automation
on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  push:
    branches: [ main ]
    paths: 
      - 'scripts/workflow_generator.py'  # Only run if generator script changes

jobs:
  generate-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git history in cleanup

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run Workflow Generator
        run: python scripts/workflow_generator.py

      - name: Commit generated workflows
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/workflows/*
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generated workflows [skip ci]"
          git push
